### ISSUE TITLE
How does one handle a really long list ?

### ISSUE THREAD

**Issue by niladam** [fourstacks/nova-checkboxes#10]
Hello,

How could one handle a large list of values ? Are there any plans/means to get this maybe in a 3 column layout ?

I'm referring both to the Form view and the index view.

**Comment by niladam** [comment]
@fourstacks - any way we could get the same layout that the columns provides on the Form view ?

**Comment by niladam** [comment]
For other people looking for a simple solution, apparently there's [a way to do this using only CSS](https://stackoverflow.com/a/6509239). However, Internet Explorer isn't supported.

This needs some manual work in order to be able to target this specific component but it shouldn't be very hard to apply this styling.

The CSS code:

```css

ul {
    -moz-column-count: 4;
    -moz-column-gap: 20px;
    -webkit-column-count: 4;
    -webkit-column-gap: 20px;
    column-count: 4;
    column-gap: 20px;
}
```

After applying this code (obviously, i have a modified version of it) and i'm using `!important` where needed i ended up with the following layout (click on the image for a larger preview):

<img width="1091" alt="screenshot 2018-11-24 17 01 59" src="https://user-images.githubusercontent.com/4151765/48969702-fecd3280-f00a-11e8-8504-cac75fbdad02.png">

After a few experiments (basically increasing the number of `column-count` and the `padding` you could even end up with a layout like the one below (column-count is ***10*** and padding is ***160px*** - my resolution is ***2560x1440*** so this might not work on lower resolutions) - click for a larger version:

<img width="1678" alt="screenshot 2018-11-24 17 04 14" src="https://user-images.githubusercontent.com/4151765/48969709-17d5e380-f00b-11e8-9465-33e86e70d33f.png">

**Comment by webspilka** [comment]
I also add 
```css
.py-6.px-8.w-1\/2{
    width: 100%;
}
```
for resize fields column from 50% to 100%
